### ISSUE TITLE
Bug with gl.join

### ISSUE THREAD

**Issue by miguel-correa92** [green-striped-gecko/dartR#123]
Good day, 

I have a large report with ca. 5000 samples split into 10 different files.  But the files do not include a `maf` column so the silent call of `gl.recalc.metrics` in `gl.join` adds it. Then if I want to add a third file, the process fails with this error:
`Error in rbind(deparse.level, ...) :  numbers of columns of arguments do not match`

I found a quick fix by calling `gl.recal.metrics` right after `gl.read.dart`. Something like this.
```
require(dartR)
require(tidyverse)
dart_data <- gl.read.dart(filename = filenames_snp[1], verbose = 0, ind.metafile = metafile) %>% 
             gl.recalc.metrics(verbose = 0)
dart2 <-     gl.read.dart(filename = filenames_snp[2], verbose = 0, ind.metafile = metafile, recalc = TRUE) %>%
             gl.recalc.metrics(verbose = 0)
dart_data_12 <- gl.join(dart_data, dart2, verbose = 1)
dart3 <-     gl.read.dart(filename = filenames_snp[3], verbose = 0, ind.metafile = metafile, recalc = TRUE) %>%
             gl.recalc.metrics(verbose = 0)
dart_data_123 <- gl.join(dart_data_12, dart3, verbose = 1)
```
The chunk of code above is just an example that works.

Best regards,

Miguel

**Comment by mijangos81** [comment]
Hi Miguel,

Thank you for reporting this bug. The gl.read.dart function has the parameter "recalc" which forces the recalculation of locus metrics. At the moment, its default is FALSE. I think the best way to deal with this would be to set the default to TRUE.

Cheers,
Luis

**Comment by biomatix** [comment]
H i Miguel,

This has been fixed in the latest version. You can now daisy-chain "joins".

All the best,

Arthur
---------------------------------------------------------------------------------------------------------------------------
*Arthur Georges*
Distinguished Professor
Institute for Applied Ecology, University of Canberra ACT 2601 Australia
Deliveries: Bld 3 Stores, Kirinari Street, Bruce ACT 2617
Tel : +61 (0)2 6201 5786  Fax: +61 (0)2 6201 5305  Mobile: +61 (0)418 866741
WWW: http://georges.biomatix.org <http://iae.canberra.edu.au/staff/georges/>
   ORCID ID: http://orcid.org/0000-0003-2428-0361
<http://orcid.org/0000-0003-2428-0361?lang=en>
Map: https://www.canberra.edu.au/maps

*       Team Pogona*

 *<**:**{**{**{{**{**{**{{}**}**}**}**}**}**}˃˃˃˃*--------

*              Ж          Ж*
