### ISSUE TITLE
Landscape genetic analysis 

### ISSUE THREAD

**Issue by laiajulianamu** [green-striped-gecko/dartR#185]
Dear developers. I am trying to make an isolation by distance but I need to build my own landscape. My question is if you have some advise that I could use for making mine, I tried with github repository but I can´t open the [landscape.sim) file

**Comment by mijangos81** [comment]
Hi Laia,

You don't need to build a landscape to perform an isolation by distance analysis, you only need your data loaded into dartR and the coordinates for each individual. You can open the help page of the function by typing: ?gl.ibd

You can also have a look at some of our tutorials, which can be downloaded from:  http://georges.biomatix.org/dartR 

Please let us know if we can help you with anything else. 

Cheers,
Luis

**Comment by green-striped-gecko** [comment]
Hi Laia,

You cannot calculate costdistances without a landscape.

For an ibd approach use gl.ibd and provide a genlight object with coordinates.

To check if you have the correct format available you can try:

gl.map.interactive(genlightobject) if this results in a map with your data then you are fine.

Cheers, Bernd



==============================================================================
Dr Bernd Gruber                                              )/_
                                                         _.--..---"-,--c_
Professor Ecological Modelling                      \|..'           ._O__)_
Tel: (02) 6206 3804                         ,=.    _.+   _ \..--( /
Fax: (02) 6201 2328                           \\.-''_.-' \ (     \_
Institute for Applied Ecology                  `'''       `\__   /\
Faculty of Science and Technology                          ')
University of Canberra   ACT 2601 AUSTRALIA
Email: ***@***.******@***.***>
WWW: bernd-gruber<https://researchprofiles.canberra.edu.au/en/persons/bernd-gruber>

Australian Government Higher Education Provider Number CRICOS #00212K
NOTICE & DISCLAIMER: This email and any files transmitted with it may contain
confidential or copyright material and are for the attention of the addressee
only. If you have received this email in error please notify us by email
reply and delete it from your system. The University of Canberra accepts
no liability for any damage caused by any virus transmitted by this email.
==============================================================================

**Comment by laiajulianamu** [comment]
Hi Bernd

Thank you for your response and sorry again for bothering you.

I have my files:
[image: image.png]


I created a gl object
gl <- gl.read.dart(filename = "YFT2.csv", ind.metafile = "meta2.csv")

and then I used:

iso <- gl.ibd(gl, projected = TRUE)
xs <- ***@***.***$latlong[, "lon"],
             pop(gl), mean)
ys <- ***@***.***$latlong[, "lat"],
             pop(gl), mean)
plot(gl)points(xs,ys, pch = 16)
text(xs, ys, popNames(gl), col = "orange")

coords <- cbind(xs, ys)
eucl <- as.matrix(dist(coords))

If I use  the "gl.map.interactive(gl)"  the map looks good but if I use the
iso object I have a error



[image: image.png]

And then when creating the cost. or when I try to create a landscape plot I
have the follow error:

cost <- costdistances(landscape = landscape.sim,
+                       locs = coords, method = "leastcost", NN =
+                         8)
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘transition’ for
signature ‘"data.frame"’
> plot(landsape.sim)
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function
'plot': object 'landsape.sim' not found
> plot(landscape.sim)
Error in plot.window(...) : need finite 'ylim' values
In addition: Warning messages:
1: In xy.coords(x, y, xlabel, ylabel, log) : NAs introduced by coercion
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf
