### ISSUE TITLE
gl.filter.secondaries creating NAs in loc.names

### ISSUE THREAD

**Issue by jennyanns** [green-striped-gecko/dartR#200]
The gl.filter.secondaries is putting NAs into the loc.names of the genlight object - I think that rather than deleting the filtered location names, it is replacing them with NA.

eg. if there were names: a,b,c,d,e,f and c and d were filtered out rather than removing c and d it is replacing them with NAs and then I think deleting e and f off the end (so you'd get a,b,NA,NA rather than a,b,e,f)

**Comment by mijangos81** [comment]
Hi,

This has been fixed in the latest version of dartR. To use this updated function you can install the developing version of dartR as describe below.

Please let us know whether it worked for you.

Cheers,
Luis 

# library required to install from github
library(devtools)
# installing developing version of dartR
install_github("green-striped-gecko/dartR@dev")

# if you are working with R-studio restart your session with menu Session -> Restart R

library(dartR)

**Comment by jennyanns** [comment]
Thank you for responding, I've tried installing that and rerun everything but it is still putting NAs in the loc.names.

**Comment by mijangos81** [comment]
Hi,

Could you please share all the commands you used before using gl.filter.secondaries. The genlight object used by dartR has three different attributes: the genotype matrix, individuals metadata and loci metadata.  You can learn more about this structure in the following tutorial: https://cran.r-project.org/web/packages/dartR/vignettes/IntroTutorial_dartR.pdf in pages 11 and 12. So, when you subset your genlight "manually" you have also to make sure to also subset the associated metadata. I suspect this is the reason you are getting those results.

Regards,
Luis

**Comment by jennyanns** [comment]
Hi Luis,

Thank you for your help - I have found an issue with one of the previous filtering steps that I must have been causing it and it does work when I follow the order of the tutorial.

Thanks,
Jenny Ann
