### ISSUE TITLE
issue to plot pcoa on populations

### ISSUE THREAD

**Issue by fernandabiologia** [green-striped-gecko/dartR#315]
Hi,

I wanted to visualise a pcoa on populations, so to do that I first calculated a distance matrix using "gl.dist.pop" and then ran a pcoa in this matrix using "gl.pcoa". In the help of the function "gl.pcoa.plot", it says that the argument x can take a Distance Matrix used to generate the ordination. I think that must be a bug on the plot function because I tried to use the distance matrix I created, but I get the error message below:

# calculate distance matrix
pop.dist <- gl.dist.pop(gl.filt, method = "euclidean")

# now do a pcoa on the pop dist matrix
dist.pop.pcoa <- gl.pcoa(pop.dist)

## plot populations 
gl.pcoa.plot(glPca = dist.pop.pcoa, x = pop.dist,  xaxis=1, yaxis=2

Starting gl.pcoa.plot 
 Error in (function (classes, fdef, mtable) : 
unable to find an inherited method for function ‘pop’ for signature ‘"dist"’

It seems to not be able to understand that the object I'm giving is of the class "dist", but according to the help of the function it should recognise it, right? 

Thanks,

Fernanda.

**Comment by mijangos81** [comment]
Hi Fernanda,

Thank you for reporting the bug. This has been fixed in the developing version of dartR. You can install this version by typing in  the R console:

library(dartR)
gl.install.vanilla.dartR(flavour = "dev")

We are about to release the second version of dartR, in which this bug has been also fixed. 

Cheers,
Luis
