### ISSUE TITLE
tdummy error on last release

### ISSUE THREAD

**Issue by LPerlaza** [green-striped-gecko/dartR#373]
Hi, 
Recently I am running into this error: 

```
gl <-gl.read.dart("Cotter Data.csv", topskip = 6, covfilename = "Cotter Covariante.csv")
Starting gl.read.dart 
Starting utils.read.dart 
  Reading in the SNP data
Error in utils.read.dart(filename = filename, nas = nas, topskip = topskip,  : 
  object 'tdummy' not found
```
This code line was working fine until recently. Is the 'tdummy' object dependent of other packages updates? I found the object in the function code but it is just a 'read.csv' read. I can't see why is unable to read it. Any suggestions to troubleshoot this? Thanks!

**Comment by mijangos81** [comment]
Hi,

Can you try the following without the parameter topskip and instead of covfilename use ind.metafile, as follows:

dartfile <- system.file('extdata','testset_SNPs_2Row.csv', package='dartR')
metadata <- system.file('extdata','testset_metadata.csv', package='dartR')
gl <- gl.read.dart(dartfile, ind.metafile = metadata)

Cheers,
Luis

**Comment by LPerlaza** [comment]
Thanks. This works. I am guessing the covfilename is deprecated now (?)

**Comment by mijangos81** [comment]
Yes!
