### ISSUE TITLE
gl.LDNe() error when mating='monogamy'

### ISSUE THREAD

**Issue by fernandabiologia** [green-striped-gecko/dartR#519]
Hi,

Thanks for adding the wrapper function gl.LDNe() to estimate Ne within R, it's very handy. I want to report what I think is a bug. 

I'm running Ne estimates for a species whose mating system is not fully understood, so I'm running both random and monogamy for comparison. When I use the function with random mating system everything works perfectly. However, when mating system = "monogamy", I get the error message below after the function completes creating the genepop file:

Completed: gl2genepop 
Error in if (mm == 0 | mm == 1) { : missing value where TRUE/FALSE needed

I think this is a bug, because to check it. I created the genpop file as I used to do in R and used that file to run the estimates directly in the NeEstimator software and it ran just fine for both mating systems. Let me know if I can help by providing data for testing.

Thanks,

Fernanda.

**Comment by green-striped-gecko** [comment]
Hi Fernanda,

Thanks for the catch, yes there is a bug, you need to specify

mating=”mono”

at this point of time as I was to lazy to type the full word in the partial match.

I will rectify this in the next version of dartR

Cheers, Bernd



==============================================================================
Dr Bernd Gruber                                              )/_
                                                         _.--..---"-,--c_
Professor Ecological Modelling                      \|..'           ._O__)_
Tel: (02) 6206 3804                         ,=.    _.+   _ \..--( /
Fax: (02) 6201 2328                           \\.-''_.-' \ (     \_
Institute for Applied Ecology                  `'''       `\__   /\
Faculty of Science and Technology                          ')
University of Canberra   ACT 2601 AUSTRALIA
Email: ***@***.******@***.***>
WWW: bernd-gruber<https://researchprofiles.canberra.edu.au/en/persons/bernd-gruber>

Australian Government Higher Education Provider Number CRICOS #00212K
NOTICE & DISCLAIMER: This email and any files transmitted with it may contain
confidential or copyright material and are for the attention of the addressee
only. If you have received this email in error please notify us by email
reply and delete it from your system. The University of Canberra accepts
no liability for any damage caused by any virus transmitted by this email.
==============================================================================

From: fernandabiologia ***@***.***>
Sent: Thursday, 20 October 2022 11:32
To: green-striped-gecko/dartR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [green-striped-gecko/dartR] gl.LDNe() error when mating='monogamy' (Issue #519)


Hi,

Thanks for adding the wrapper function gl.LDNe() to estimate Ne within R, it's very handy. I want to report what I think is a bug.

I'm running Ne estimates for a species whose mating system is not fully understood, so I'm running both random and monogamy for comparison. When I use the function with random mating system everything works perfectly. However, when mating system = "monogamy", I get the error message below after the function completes creating the genepop file:

Completed: gl2genepop
Error in if (mm == 0 | mm == 1) { : missing value where TRUE/FALSE needed

I think this is a bug, because to check it. I created the genpop file as I used to do in R and used that file to run the estimates directly in the NeEstimator software and it ran just fine for both mating systems. Let me know if I can help by providing data for testing.

Thanks,

Fernanda.

**Comment by fernandabiologia** [comment]
Thanks for the quick reply Bernd. It works with mating = "mono" :)

Cheers,

Fernanda.
