### ISSUE TITLE
Problems with gl2svdquartets

### ISSUE THREAD

**Issue by abcosta** [green-striped-gecko/dartR#52]
Hi,

I'm trying to use gl2svdquartets but I keep getting the following error message:

`gl2svdquartets(gl, outfile="svd.nex", outpath=getwd(), method=1)`
_Starting gl2svdquartets: Create nexus file
Extacting SNP bases and creating records for each individual_
**Error in strsplit(snp, ">") : non-character argument**

I'm converting my vcf file to genlight object using vcfR2genlight, and then using it to convert to the svdquartets format. Do have any suggestion about what can be causing this error message?

Thank you,
Ana

**Comment by arthurgeorges** [comment]
Dear Ana,

It works OK for me so I cannot understand why you are getting that message.
The only thing I can suggest is that when converting from vcfR2genlight,
the slot

x@other$loc.metrics$SNP

is not being populated properly. This vector should contain data like

19:A>G


which is decomposed by the script.

Because the data for  x@other$loc.metrics$SNP is not correct, the code

  snp <- as.character(x@other$loc.metrics$SNP)
  snp <- strsplit(snp,":")
  snp <- unlist(lapply(snp, `[`, 2))
  snp <- strsplit(snp,">")

falls over.

Bernd, as you wrote the scripts to bring in data from other applications,
can you check this?

Arthur



----------------------------------------------------------------------------------------------------------------------------
*D-Prof. Arthur Georges*
Institute for Applied Ecology, University of Canberra ACT 2601 Australia
Deliveries: Bld 3 Stores, Kirinari Street, Bruce ACT 2617
Tel : +61 (0)2 6201 5786  Fax: +61 (0)2 6201 5305  Mobile: +61 (0)418 866741
WWW: http://georges.biomatix.org <http://iae.canberra.edu.au/staff/georges/>
   ORCID ID: http://orcid.org/0000-0003-2428-0361
<http://orcid.org/0000-0003-2428-0361?lang=en>

**Comment by arthurgeorges** [comment]
Hi Ana,

I have had another look at this, and can see the problem. Package dartR is
designed to work with data supplied by Diversity Arrays Technology, which
has a specific format. In addition to the SNP calls, it has a range of
locus metadata (call rate, repAvg, etc) and user supplied sample metadata
(id, sex, etc).

One locus metadata column is SNP which is of the format 19:A>G which means
at position 20 (it is indexed from zero) of the sequence tag, the reference
allele has an A and the alternate allele has a G.

gl2svdquartets uses this information to create the input data for
svdquartets.

vcfR2genlight does a very basic job of creating the genlight object,
without passing much metadata across. Indeed, there appears to be loss of
information in the conversion.

So unless you can create your genlight object manually, to comply with the
dartR genlight format, it is going to be difficult. It would be easier to
create the svd nexus file manually I suspect.

Sorry I can not be of further help.

Arthur

**Comment by abcosta** [comment]
Dear Arthur,

Thank you for your messages.
I was planning to use dartR to compare it with the method I'm current using, but that's okay.
I really appreciate your attention to this subject.

Best,
Ana

**Comment by arthurgeorges** [comment]
No probs.

A

----------------------------------------------------------------------------------------------------------------------------
*D-Prof. Arthur Georges*
Institute for Applied Ecology, University of Canberra ACT 2601 Australia
Deliveries: Bld 3 Stores, Kirinari Street, Bruce ACT 2617
Tel : +61 (0)2 6201 5786  Fax: +61 (0)2 6201 5305  Mobile: +61 (0)418 866741
WWW: http://georges.biomatix.org <http://iae.canberra.edu.au/staff/georges/>
   ORCID ID: http://orcid.org/0000-0003-2428-0361
<http://orcid.org/0000-0003-2428-0361?lang=en>
