### ISSUE TITLE
Problem with dartR installation 

### ISSUE THREAD

**Issue by AndriiTarieiev** [green-striped-gecko/dartR#520]
Dear developers,

I tried to install dartR using R 3.6.3, 4.0.3, 4.1.0, and 4.1.1 on HPC (SCientific Linux7.9), and also locally using R 4.2.0 and 4.2.1 on Windows 10 and 11, and Ubuntu 20.04 and 22.04. directly from R, from Github, and from Bioconductor.
In all the cases installation fails with the following error message:

ERROR: dependencies ‘PopGenReport’, ‘raster’ are not available for package ‘dartR’
* removing ...
Warnings:
1: In i.p(...) : installation of package ‘terra’ had non-zero exit status
2: In i.p(...) : installation of package ‘raster’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘gdistance’ had non-zero exit status
4: In i.p(...) : installation of package ‘dismo’ had non-zero exit status
5: In i.p(...) :
  installation of package ‘PopGenReport’ had non-zero exit status
6: In i.p(...) :
  installation of package ‘/tmp/RtmpfOADMG/file2307c514e5044/dartR_2.1.4.tar.gz’ had non-zero exit status

I would appreciate it very much if you are able to suggest how it can be fixed. 
Thank you.

**Comment by green-striped-gecko** [comment]
Hi Andrii,

based on the error message the package installation fails because some other packages failed to install. you need to crawl through them in order.

the first package that fails is terra, so please check howto install terra on ubuntu (i recall i had some problems with terra on redhat as well). it needs to compile and has also gdal as dependency which often fails to install. check the help sites for terra.
test if install via
library(terra).

then try to reinstall dartr. if there are still other packages that fail, then try to install them with their help pages.

the good news all the packages listed down from terra (gdistance, raster, popgenreport) depend on terra, hence it may be the only package that causes problems but hard to predict,

hope that helps,
Bernd


—————————————————————————————————————

Bernd Gruber

Professor Spatial and Ecological Modelling

Institute for Applied Ecology

P 02 620638<tel:02%2062063824>04  E ***@***.******@***.***>

appliedecology.edu.au<http://appliedecology.edu.au/>

University of Canberra, ACT 2617

[cid:773E8FD9-259B-42DE-B032-8786C1547AA3]

NOTICE & DISCLAIMER: This email and any files transmitted with it may contain confidential or copyright materials and are for the attention of the addressee only. If you have received this email in error please notify us by email reply and delete it from your system. The University of Canberra accepts no liability for any damage caused by any virus transmitted by this email.Australian Government Higher Education (CRICOS)Registered Provider number: #00212K
—————————————————————————————————————

On 20 Oct 2022, at 20:35, AndriiTarieiev ***@***.***> wrote:

﻿

Dear developers,

I tried to install dartR using R 3.6.3, 4.0.3, 4.1.0, and 4.1.1 on HPC (SCientific Linux7.9), and also locally using R 4.2.0 and 4.2.1 on Windows 10 and 11, and Ubuntu 20.04 and 22.04. directly from R, from Github, and from Bioconductor.
In all the cases installation fails with the following error message:

ERROR: dependencies ‘PopGenReport’, ‘raster’ are not available for package ‘dartR’

  *   removing ...
Warnings:
1: In i.p(...) : installation of package ‘terra’ had non-zero exit status
2: In i.p(...) : installation of package ‘raster’ had non-zero exit status
3: In i.p(...) :
installation of package ‘gdistance’ had non-zero exit status
4: In i.p(...) : installation of package ‘dismo’ had non-zero exit status
5: In i.p(...) :
installation of package ‘PopGenReport’ had non-zero exit status
6: In i.p(...) :
installation of package ‘/tmp/RtmpfOADMG/file2307c514e5044/dartR_2.1.4.tar.gz’ had non-zero exit status

I would appreciate it very much if you are able to suggest how it can be fixed.
Thank you.

**Comment by AndriiTarieiev** [comment]
Dear Bernd,

Thank you for your suggestion. I found that package "terra" has a problem with GDAL, and the latter cannot be updated for some reason, so I need to search further.

Best regards,
Andrii

**Comment by AndriiTarieiev** [comment]
Dear Luis,

I followed the installation tutorial but the failure at the end remains the same.

Best,
Andrii

**Comment by mijangos81** [comment]
Hi Andrii:

Could you please confirm whether you started the installation tutorial from step 1?

Cheers,
Luis

**Comment by AndriiTarieiev** [comment]
Hi Luis,

Yes, I started it from the step 1

Best,
Andrii

**Comment by mijangos81** [comment]
Hi Andrii,

Can you try using the installation instructions of the package terra from their GitHub page:

https://github.com/rspatial/terra

Cheers,
Luis
