### ISSUE TITLE
issue with gl.impute() when method="neighbour"

### ISSUE THREAD

**Issue by zdzbinden** [green-striped-gecko/dartR#567]
Hello!

I was using gl.impute() using the "neighbour" method and it seemed to work fine until I set fill.residual = FALSE. 

I realized that all along "neighbour" was not working and the imputation was just randomly imputing based on global frequencies.

I played around with the code and realized at line 241 of gl.impute.r, I was getting an empty matrix for pw_dis_2. This caused the remaining objects to also be empty and the warning: "  No more individuals left to impute individual" for all individuals.

I think the issue is at the beginning of the for loop on line 239. Instead of looping over the individual number, I think it should instead loop over the individual name.

This appears to work for me.

**Comment by zdzbinden** [comment]
The original code does work if Individuals in the genlight object are first renamed:
`indNames(genlight) <- seq(1:nInd(genlight)`

**Comment by mijangos81** [comment]
Hi,

Thank you for reporting this bug. 

As you correctly noted, the problem was in line 241:

> pw_dis_2 <- pw_dis[which(ind == pw_dis$Var1), ]

Which should be:

> pw_dis_2 <- pw_dis[which(indNames(x)[ind] == pw_dis$Var1), ]

This fix is now available in the beta version of dartR, which can be installed as follows:

library(dartR)
gl.install.vanilla.dartR(flavour = "beta")

If you are interested, here are some results of the testing of the function gl.impute, compared with the null case (random imputation).

In the attached figure, each panel is one method. The labels in the legend are the values of the 4 variables tested:
- first variable is percentage of missing data, 
- second is selection (TRUE or FALSE)
- third is dispersal (TRUE or FALSE)
- fourth is the percentage of individuals that were sampled from the whole population.

I am attaching the files required (sim_variables.csv, ref_variables.csv) to run the code (test_imputation.r) that took around ten minutes to run on my computer. 

Cheers,
Luis

[imputation.zip](https://github.com/green-striped-gecko/dartR/files/10348122/imputation.zip)
[test_imputation.pdf](https://github.com/green-striped-gecko/dartR/files/10348126/test_imputation.pdf)
