### ISSUE TITLE
dartR - Installation problems using Ubuntu

### ISSUE THREAD

**Issue by abcosta** [green-striped-gecko/dartR#60]
Hi,
I have recently started to use Linux (I'm still not very familiar with it) and I am having problems to install dartR. I'm using RStudio and when I try to follow the recommended steps I received the following message:

**_"package dartR is not available (for R version 3.2.3)"_**

I checked for updates of RStudio and it says that I am using the newest version. Therefore I am not sure how to fix this problem. Do you have any recommendations?

Thanks!!

**Comment by arthurgeorges** [comment]
Hi abcosta,

I am afraid that Bernd Gruber is on leave for two weeks and out of contact. However he has advised that CRAN has pulled the dartR package pending resolution of some issue (which does not have anything to do with dartR apart from a problematic dependency on PogGenReport). He cannot fix it until he gets back, but has advised that the installation from GitHub should be fine. Are you able to do that?

install.packages("devtools")
library(devtools)
install_github("green-striped-gecko/dartR")
library(dartR)

or if there are issues with the SNPRelate dependencies

install.packages("devtools")
library(devtools)
install.packages("BiocManager")
BiocManager::install(c("SNPRelate", "qvalue"))
install_github("green-striped-gecko/dartR")
library(dartR)

Sorry for the bother.

Arthur

**Comment by abcosta** [comment]
Dear Arthur,

Thank you for your email.

I tried the first code and it installed 15 packages but none of them were dartR. When I used the “library(dartR)” I received the message “there is no package called dartR”.
I tried the second code, but it said that BiocManager wasn’t available, so I used the other code in the GitHub:

source("https://bioconductor.org/biocLite.R")
BiocInstaller::biocLite(c("SNPRelate", "qvalue"))
install.packages("dartR")
library(dartR)
However, it gave me the same answer:

“package dartR is not available (for R version 3.2.3)”

It usually works in my mac but it isn’t in the Linux pc I need to use to run the analyses. I guess I will wait until Bernd Gruber comes back.
If I figure out how to fix this problem, I will let you know.

Thank you,
Ana

**Comment by jennyovenden** [comment]
Hi Arthur - I've having the same problems installing dartR as Ana (above). Can you let me know when you are able to fix this issue? Thanks, Jenny Ovenden (j.ovenden@uq.edu.au)

**Comment by green-striped-gecko** [comment]
Hi Ana,

Did you manage to install?

Cheers, Bernd

Ps I just submitted a new version to CRAN and if accepted dartR should be back on cran in the coming days.




==============================================================================
Dr Bernd Gruber                                              )/_
                                                         _.--..---"-,--c_
Associate Professor                                 \|..'           ._O__)_
Tel: (02) 6206 3804                         ,=.    _.+   _ \..--( /
Fax: (02) 6201 2328                           \\.-''_.-' \ (     \_
Institute for Applied Ecology                  `'''       `\__   /\
Faculty of Science and Technology                          ')
University of Canberra   ACT 2601 AUSTRALIA
Email: bernd.gruber@canberra.edu.au<mailto:bernd.gruber@canberra.edu.au>
WWW: bernd-gruber<https://researchprofiles.canberra.edu.au/en/persons/bernd-gruber>

Australian Government Higher Education Provider Number CRICOS #00212K
NOTICE & DISCLAIMER: This email and any files transmitted with it may contain
confidential or copyright material and are for the attention of the addressee
only. If you have received this email in error please notify us by email
reply and delete it from your system. The University of Canberra accepts
no liability for any damage caused by any virus transmitted by this email.
==============================================================================

**Comment by green-striped-gecko** [comment]
gl2csvmatrix <- function(x, outpath=getwd(), outfile="test.csv")
{
mm <- data.frame(as.matrix(x))
write.csv(mm,file = file.path(outpath, outfile), row.names = T)
}

==============================================================================
Dr Bernd Gruber       Tel: (02) 6206 3804 Fax: (02) 6201 2328
Associate Professor
Institute for Applied Ecology
Faculty of Applied Science
University of Canberra   ACT 2601 AUSTRALIA
Email: bernd.gruber@canberra.edu.au<mailto:bernd.gruber@canberra.edu.au>
WWW: http://www.canberra.edu.au/faculties/science/staff/profiles/dr-bernd-gruber

Australian Government Higher Education Provider Number CRICOS:#00212K

NOTICE & DISCLAIMER: This email and any files transmitted with it may contain
confidential or copyright material and are for the attention of the addressee
only. If you have received this email in error please notify us by email
reply and delete it from your system. The University of Canberra accepts
no liability for any damage caused by any virus transmitted by this email.

==============================================================================

[UC Logo]<http://www.canberra.edu.au>           [UC is switching off for Earth Hour]


[UC Facebook]<https://www.facebook.com/UniversityOfCanberra>[UC Twitter]<https://twitter.com/UniCanberra>[UC Instagram]<https://www.instagram.com/unicanberra/>[UC Youtube]<https://www.youtube.com/user/uniofcanberra>         [University of Canberra] <http://www.canberra.edu.au>   *QILT 2018

Australian Government Higher Education Registered Provider (CRICOS) #00212K


The University of Canberra acknowledges the Ngunnawal people, traditional custodians of the lands where Bruce Campus is situated. We wish to acknowledge and respect their continuing culture and the contribution they make to the life of Canberra and the region. We also acknowledge all other First Nations Peoples on whose lands we gather.


NOTICE AND DISCLAIMER: This email and any files transmitted with it may contain confidential or copyright materials and are for the attention of the addressee only. If you have received this email in error please notify us by email reply and delete it from your system. The University of Canberra accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by pezhmansafdari** [comment]
Hi,
A lot of dartR dependencies do not exist on CRAN anymore and have moved to GitHub. The dartR installer is still searching for them in CRAN. I ended up installing all of the dependencies separately from GitHub manually to install the package. 

BR,
Pezhman

**Comment by green-striped-gecko** [comment]
Hi Pezhman,

Can you be a bit more specific which packages are no longer on CRAN and yes I agree dartR (and other packages) on linux are a pain (e.g. you need to install quite some dependencies such as gdal, rgl etc. by hand).

I am aware that SNPrelate and qvalues (and their dependencies are on Bioconductor).

Cheers ,Bernd



==============================================================================
Dr Bernd Gruber                                              )/_
                                                         _.--..---"-,--c_
Associate Professor                                 \|..'           ._O__)_
Tel: (02) 6206 3804                         ,=.    _.+   _ \..--( /
Fax: (02) 6201 2328                           \\.-''_.-' \ (     \_
Institute for Applied Ecology                  `'''       `\__   /\
Faculty of Science and Technology                          ')
University of Canberra   ACT 2601 AUSTRALIA
Email: bernd.gruber@canberra.edu.au<mailto:bernd.gruber@canberra.edu.au>
WWW: bernd-gruber<https://researchprofiles.canberra.edu.au/en/persons/bernd-gruber>

Australian Government Higher Education Provider Number CRICOS #00212K
NOTICE & DISCLAIMER: This email and any files transmitted with it may contain
confidential or copyright material and are for the attention of the addressee
only. If you have received this email in error please notify us by email
reply and delete it from your system. The University of Canberra accepts
no liability for any damage caused by any virus transmitted by this email.
==============================================================================

**Comment by pezhmansafdari** [comment]
Hi,

I had to install  "Hmisc", "rms" from CRAN separately and then "gdsfmt",
"SNPRelate" and "qvalue" from GitHub. Installing "gdal" is another big
effort but, fortunately, our IT people did that for me.

Cheers,
Pezhman

**Comment by pezhmansafdari** [comment]
Hi Bernd,

I want to calculate nucleotide diversity (pi) for my DArT.csv data. I know
how to do it with a VCF file but not DArt file. Is there any way to
calculate the pi directly fron DArT data or any software which can convert
DArT to VCF?

**Comment by biomatix** [comment]
Hi Pezhman,

I think pi is defined as the number of differences per locus between the
two sequence tags (SNPs being biallelic) averaged across all individuals in
a given population, and expressed as a proportion.

So if we consider one SNP locus across 5 individuals in 1 population

Individual   1   2   3   4   5
Genotype     2   1   0   1   1
Difference   0   1   0   1   1

only the heterozygotes contribute to pi. So for the DArT data, the value of
pi is the proportion of heterozygotes averaged across all individuals in
the population.

Essentially the same as heterozygosity, depending on how you handle missing
values.

If you want to calculate it directly, try

gl <- testset.gl
gl <- gl.filter.secondaries(gl)
gl <- gl.filter.monomorphs(gl)
gl <- gl.recalc.metrics(gl) # Just to be sure
nLoc(gl)
nInd(gl)

m <- as.matrix(gl)
s <- sum(m[m==1],na.rm=T)
n <- length(m[!is.na(m)])
pi <- s/n

Maybe try this on a dataset where you know the correct answer.

Hope this helps.

A
