### ISSUE TITLE
gl.filter.repavg -- not working

### ISSUE THREAD

**Issue by jennyovenden** [green-striped-gecko/dartR#62]
Hi DARTR team,

The tutorial says "CloneID is essential (with its very special format), and dartR scripts for loading your data sets will terminate with an error message if this is not present."

I have DART data without 'CloneID' field. The data loaded OK into a genlight object. The console said 
.
.
Try to add covariate file: xxx_2018_metadata.csv .
Ids of covariate file (at least a subset of) are matching!
Found  147 matching ids out of 147 ids provided in the covariate file. Subsetting snps now!.
 Added pop factor.
Please note:there is no lat column
Please note:there is no lon column
Added  id  to the other$ind.metrics slot.
 Added  pop  to the other$ind.metrics slot.
Warning message:
In .local(.Object, ...) :
  Miss-formed strings in loc.all (must be e.g. 'c/g') - storing this argument in @other.

Could the lack of CloneID be causing gl.filter.repavg to return "[1] NA" when I request number of loci (nLoc) after using filter? The number of individuals (nInd) is correct after filtering.

I duplicated the AlleleID column and called it CloneID in the DART.csv but this didn't allow the filter to proceed.

Any ideas?

Thanks, Jenny

**Comment by green-striped-gecko** [comment]
Hi Jenny,

This is outdated. Should read now AlleleID is essential. So the import should work.

What does not seem to work is your SNP information. Maybe some other columns are missing or RepAvg is not the last column?


In .local(.Object, ...) :
Miss-formed strings in loc.all (must be e.g. 'c/g') - storing this argument in @other<https://github.com/other>.
Can you show me what is stored under @other

And copy the colnames of your dart csv file.

Cheers,Bernd


==============================================================================
Dr Bernd Gruber                                              )/_
                                                         _.--..---"-,--c_
Associate Professor                                 \|..'           ._O__)_
Tel: (02) 6206 3804                         ,=.    _.+   _ \..--( /
Fax: (02) 6201 2328                           \\.-''_.-' \ (     \_
Institute for Applied Ecology                  `'''       `\__   /\
Faculty of Science and Technology                          ')
University of Canberra   ACT 2601 AUSTRALIA
Email: bernd.gruber@canberra.edu.au<mailto:bernd.gruber@canberra.edu.au>
WWW: bernd-gruber<https://researchprofiles.canberra.edu.au/en/persons/bernd-gruber>

Australian Government Higher Education Provider Number CRICOS #00212K
NOTICE & DISCLAIMER: This email and any files transmitted with it may contain
confidential or copyright material and are for the attention of the addressee
only. If you have received this email in error please notify us by email
reply and delete it from your system. The University of Canberra accepts
no liability for any damage caused by any virus transmitted by this email.
==============================================================================

**Comment by jennyovenden** [comment]
Hi Bernd - Thanks, will be able to respond on Monday. I appreciate your assistance. Best, Jenny

On 14 Mar 2019, at 4:55 pm, Bernd Gruber <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Jenny,

This is outdated. Should read now AlleleID is essential. So the import should work.

What does not seem to work is your SNP information. Maybe some other columns are missing or RepAvg is not the last column?


In .local(.Object, ...) :
Miss-formed strings in loc.all (must be e.g. 'c/g') - storing this argument in @other<https://github.com/other>.
Can you show me what is stored under @other

And copy the colnames of your dart csv file.

Cheers,Bernd


==============================================================================
Dr Bernd Gruber )/_
_.--..---"-,--c_
Associate Professor \|..' ._O__)_
Tel: (02) 6206 3804 ,=. _.+ _ \..--( /
Fax: (02) 6201 2328 \\.-''_.-' \ ( \_
Institute for Applied Ecology `''' `\__ /\
Faculty of Science and Technology ')
University of Canberra ACT 2601 AUSTRALIA
Email: bernd.gruber@canberra.edu.au<mailto:bernd.gruber@canberra.edu.au><mailto:bernd.gruber@canberra.edu.au>
WWW: bernd-gruber<https://researchprofiles.canberra.edu.au/en/persons/bernd-gruber>

Australian Government Higher Education Provider Number CRICOS #00212K
NOTICE & DISCLAIMER: This email and any files transmitted with it may contain
confidential or copyright material and are for the attention of the addressee
only. If you have received this email in error please notify us by email
reply and delete it from your system. The University of Canberra accepts
no liability for any damage caused by any virus transmitted by this email.
==============================================================================

**Comment by jennyovenden** [comment]
Hi Bernd

Attached is an .xls (two worksheets) with the information you requested below.

Your help is greatly appreciated.

Thanks, Jenny

On 14 Mar 2019, at 4:55 pm, Bernd Gruber <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Jenny,

This is outdated. Should read now AlleleID is essential. So the import should work.

What does not seem to work is your SNP information. Maybe some other columns are missing or RepAvg is not the last column?


In .local(.Object, ...) :
Miss-formed strings in loc.all (must be e.g. 'c/g') - storing this argument in @other<https://github.com/other>.
Can you show me what is stored under @other

And copy the colnames of your dart csv file.

Cheers,Bernd


==============================================================================
Dr Bernd Gruber )/_
_.--..---"-,--c_
Associate Professor \|..' ._O__)_
Tel: (02) 6206 3804 ,=. _.+ _ \..--( /
Fax: (02) 6201 2328 \\.-''_.-' \ ( \_
Institute for Applied Ecology `''' `\__ /\
Faculty of Science and Technology ')
University of Canberra ACT 2601 AUSTRALIA
Email: bernd.gruber@canberra.edu.au<mailto:bernd.gruber@canberra.edu.au><mailto:bernd.gruber@canberra.edu.au>
WWW: bernd-gruber<https://researchprofiles.canberra.edu.au/en/persons/bernd-gruber>

Australian Government Higher Education Provider Number CRICOS #00212K
NOTICE & DISCLAIMER: This email and any files transmitted with it may contain
confidential or copyright material and are for the attention of the addressee
only. If you have received this email in error please notify us by email
reply and delete it from your system. The University of Canberra accepts
no liability for any damage caused by any virus transmitted by this email.
==============================================================================

**Comment by shandiya** [comment]
Hi Bernd,

I was wondering if this issue has been resolved? I'm having the same problem when I try to read in the SNP and metadata files. I get the following warning message: 

Warning message:
In .local(.Object, ...) :
Miss-formed strings in loc.all (must be e.g. 'c/g') - storing this argument in @other.

When I check what's stored in @other by calling gl@other$loc.all.misformed, I get this printout:

 "G/A" "A/G" "T/C" "C/T" "G/T" "C/T" "T/C" "T/A" "A/G" "C/A" "A/G" "G/A" "C/T" "A/G" "T/C" "T/C" "G/A" "C/T" "G/A" "A/G" "C/T" "G/C" "G/T" "G/A" "A/G" "T/C" "T/G" "G/T" "C/A" "G/A" "T/C" "A/G" "A/G" "T/C" "C/T" "G/T" "G/A" "G/A" "G/A" "T/C" "G/A" "A/G" "G/A" "A/T" "A/G" "G/T" "G/T" "G/A" "A/G" "T/C" "G/A" "T/C" "G/A" "C/A" "C/T" "G/T" "G/A" "C/T" "G/A" "G/T" "C/T" "C/T" "A/G" "G/T" "T/G" "C/T" "A/G" "T/A" "C/T" "G/C" "G/C" "A/G" "G/A" "C/T" "T/C" "G/A" "G/A" "A/G" "G/A" "T/C" "A/C" "G/A" "A/G" "T/C" "T/C" "G/T" "C/T" "G/A" "A/T" "C/A" "G/A" "A/G" "C/T" "G/A" "C/T" "T/C" "A/T" "A/G" "A/G" "A/C" "G/T" "G/A" "A/G" "T/C" "A/G" "A/G" "T/C" "A/G" "A/C" "C/G" "C/T" "G/A" "C/T" "C/A" "C/T" "C/T" "A/G" "T/A" "G/A" "C/T" "A/G" "A/C" "C/T" "C/T" "G/C" "C/T" "T/C" "C/T" which goes on for a bit in the same vein, then reaches the max print point. 

Thanks for your help!

Cheers,
Shandiya

**Comment by shandiya** [comment]
In case this helps, these are the colnames of my SNP data file:

AlleleID | CloneID | AlleleSequence | TrimmedSequence | SNP | SnpPosition | CallRate | OneRatioRef | OneRatioSnp | FreqHomRef | FreqHomSnp | FreqHets | PICRef | PICSnp | AvgPIC | AvgCountRef | AvgCountSnp | RepAvg | Ind1 | Ind 2 etc.

Shandiya
