### ISSUE TITLE
`recalc =TRUE` should be default

### ISSUE THREAD

**Issue by konopinski** [green-striped-gecko/dartR#653]
Hi,
I have been playing around with my data and at a certain moment I have noticed my results became odd. The reason is I have forgotten adding `recalc = TRUE` at one of the filtering steps (callrate). Don't you think recalc should be set TRUE as a default? I belive many people do not even realize metadata in their object might not be correct. I am not a newbie in R but still it happend to me. 
Cheers
Maciek
By the way, DartR is one of my favourite packages.

**Comment by biomatix** [comment]
Hi Maciek,

Great to hear that dartR is one of your favourite packages. Positive
feedback is always welcome.

The reason we had recalc=FALSE as the default was because it was
computationally expensive. As a consequence, you do not want the recalc to
run on each filter in your sequence of filtering steps. The idea is that
you would set it to TRUE only on the last filter you planned to run.

Since then though, we have established an environment attached to each
genlight object in which flags are set when the recalc is or is not
necessary for particular variables in the locus metrics. So I guess we
could set the default to TRUE, as the computational overheads are gone. Not
sure if that would create issues for other users who are now used to the
default being FALSE.

We will talk about it in the dev team. Thanks for raising it.

A
