### ISSUE TITLE
gl.diversity inoperable on Linux

### ISSUE THREAD

**Issue by shofmon88** [green-striped-gecko/dartR#85]
Hi Bernd,

I am using a fresh install of R and RStudio on a brand new computer with Pop!_OS 18.04, and I noticed that when computing Shannon Diversity, the function outputs straight 1s for every metric. I have not had the same issue on my Mac, even with the same version of R and dartR. The remainder of dartR appears to function as normal, that is filtering and other functions produce identical outputs to my Mac. I have also used gl.diversity on Ubuntu/Pop!_OS before without any issue, though that was quite a while ago. I am using the same dataset that I provided you in 2018 to help write the function. Any ideas? Thanks in advance for helping with this.

**Comment by green-striped-gecko** [comment]
Hi can you please check which version of Adegenet you are using on each system.

The latest version of adegenet 1.2.2 (if I am not mistaken) has a buggy implementation of the seppop command which is used by gl.diversity.

I recommended in a post earlier on our google group to downgrade to 1.2.1 (which did not have the problem).

Cheers, Bernd



==============================================================================
Dr Bernd Gruber                                              )/_
                                                         _.--..---"-,--c_
Associate Professor                                 \|..'           ._O__)_
Tel: (02) 6206 3804                         ,=.    _.+   _ \..--( /
Fax: (02) 6201 2328                           \\.-''_.-' \ (     \_
Institute for Applied Ecology                  `'''       `\__   /\
Faculty of Science and Technology                          ')
University of Canberra   ACT 2601 AUSTRALIA
Email: bernd.gruber@canberra.edu.au<mailto:bernd.gruber@canberra.edu.au>
WWW: bernd-gruber<https://researchprofiles.canberra.edu.au/en/persons/bernd-gruber>

Australian Government Higher Education Provider Number CRICOS #00212K
NOTICE & DISCLAIMER: This email and any files transmitted with it may contain
confidential or copyright material and are for the attention of the addressee
only. If you have received this email in error please notify us by email
reply and delete it from your system. The University of Canberra accepts
no liability for any damage caused by any virus transmitted by this email.
==============================================================================

**Comment by shofmon88** [comment]
Thanks Bernd, downgrading to adegenet 2.1.1 solved it. But now I have a different issue. I would like to use the Shannon matrix for an IBD plot. If I do:

shannon.decoris <- gl.diversity(gl.final.decoris)

gl.ibd(gl.final.decoris, Dgen = shannon.decoris$one_H_beta)

the gl.ibd function still uses Fst/1-Fst as the diversity measure.

Thanks again.

**Comment by green-striped-gecko** [comment]
Best at this stage to plot by hand.

I will work on the gl.ibd at some time.

So
plot (as.dist(eucl-distancematrix), as.dist(gendistancematrix))

And use the mantel test from vegan.

Or check the adegenet vignette for such a plot.

---------


On 29 Feb 2020, at 13:48, Ryan Shofner <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Bernd, downgrading to adegenet 2.1.1 solved it. But now I have a different issue. I would like to use the Shannon matrix for an IBD plot. If I do:

shannon.decoris <- gl.diversity(gl.final.decoris)

gl.ibd(gl.final.decoris, Dgen = shannon.decoris$one_H_beta)

the gl.ibd function still uses Fst/1-Fst as the diversity measure.

Thanks again.
