### ISSUE TITLE
gl.read.silicodart and gl2gi for silicodart

### ISSUE THREAD

**Issue by yrodger** [green-striped-gecko/dartR#88]
Hi Bernd and Arthur,

I understand this is a work in progress but in help("gl.read.silicodart") it says that the resulting object should be of class "genInd" but when I used this function my object turned out to be a genlight, similar to with DArTseq. I was then able to perform filtering as normal and even PCoAs (which is great!).
However, when I used "gl2gi" to convert my silicodart genlight into a genind, it results in a co-dominant data genind with 0, 1, 2 instead of a presence/absence 0,1, NA object as I would have expected. The ploidy also becomes 2 instead of 1 in the new genind. Is this function not available yet for silicodart?

Cheers,

Yael

**Comment by green-striped-gecko** [comment]
Hi,

yes the gl2gi function does not work for silicodart yet.
And also the help file is incorrect. there was once a function that created a gen8nd object from silicodart data, but this was abandoned and the read function creates a genlight object.

apologies for the confusion this will be rectified in the next update.

Cheers, Bernd


—————————————————————————————————

Bernd Gruber

Associate Professor

Spatial and Ecological Modelling

Institute for Applied Ecology

P 02 620638<tel:02%2062063824>04  E bernd.gruber@canberra.edu.au<mailto:amy.dobos@canberra.edu.au>

appliedecology.edu.au<http://appliedecology.edu.au/>

University of Canberra, ACT 2617


NOTICE & DISCLAIMER: This email and any files transmitted with it may contain confidential or copyright materials and are for the attention of the addressee only. If you have received this email in error please notify us by email reply and delete it from your system. The University of Canberra accepts no liability for any damage caused by any virus transmitted by this email.Australian Government Higher Education (CRICOS)Registered Provider number: #00212K
—————————————————————————————————

On 11 Jun 2020, at 14:59, yrodger <notifications@github.com> wrote:

﻿

Hi Bernd and Arthur,

I understand this is a work in progress but in help("gl.read.silicodart") it says that the resulting object should be of class "genInd" but when I used this function my object turned out to be a genlight, similar to with DArTseq. I was then able to perform filtering as normal and even PCoAs (which is great!).
However, when I used "gl2gi" to convert my silicodart genlight into a genind, it results in a co-dominant data genind with 0, 1, 2 instead of a presence/absence 0,1, NA object as I would have expected. The ploidy also becomes 2 instead of 1 in the new genind. Is this function not available yet for silicodart?

Cheers,

Yael

**Comment by yrodger** [comment]
Thanks Bernd. Just to be clear - I can trust the results I got from gl.pcoa using the silicoDArT genlight? There is no issue with this functionality is there?

**Comment by green-striped-gecko** [comment]
no that is fine.

Cheers, Bernd


—————————————————————————————————

Bernd Gruber

Associate Professor

Spatial and Ecological Modelling

Institute for Applied Ecology

P 02 620638<tel:02%2062063824>04  E bernd.gruber@canberra.edu.au<mailto:amy.dobos@canberra.edu.au>

appliedecology.edu.au<http://appliedecology.edu.au/>

University of Canberra, ACT 2617


NOTICE & DISCLAIMER: This email and any files transmitted with it may contain confidential or copyright materials and are for the attention of the addressee only. If you have received this email in error please notify us by email reply and delete it from your system. The University of Canberra accepts no liability for any damage caused by any virus transmitted by this email.Australian Government Higher Education (CRICOS)Registered Provider number: #00212K
—————————————————————————————————

On 12 Jun 2020, at 13:21, yrodger <notifications@github.com> wrote:

﻿

Thanks Bernd. Just to be clear - I can trust the results I got from gl.pcoa using the silicoDArT genlight? There is no issue with this functionality is there?
